name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      # This step is needed if you're building multi-architecture images, such as ARM64 on x86_64.

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mbaelde/churn-prediction-poc:latest
      # Replace "latest" with the tag you want to use for your image.

    - name: Push the Docker image to Docker Hub
      run: docker push mbaelde/churn-prediction-poc:latest
      # Replace "latest" with the tag you used when building the image.
